ANSIBLE_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:zdCU+ln43NjfrBS+cqdqaMuQYKHtyxdkW/nTOFT603q3QbHASbd8ihvHu4pqR0Fn7v1pOKBMBljK2TSV3OMQAog+u1G2ZS6G/QUxOQBAAuONE1nH8IolCfdqQwtET83V34WclYnUf6Da0p+Pgxpt3NEXvRSifsJESTbFaG25OpPb9eSOyZvGAyQOWDxnE9jmMPstGElfu4O8Ko35lx08LFFTHvsB6mga4fK+dk1nSnP+BgAwE4R1Ko24kH1Sl46buP4Zmsb2cwY4TqNKBxfu3vObrOR5uo7D3yJBiTh7Ic1XUhramJwaJ6zB+BDYcz8Qr7G1tgnrA70cmsgEBif3gcQUtdbnNWy2V/C/0XuCF+jHA4p+tgc3Y5QhWE3BM4g+KqhV1wVyIhlBiFWJp0UhcbUbqGdmsHtMUcUGD/S1e3NVaBFpnO5ktrbxh6h0shcgJh3mzLkBiyo/QvxyHVQbpO62hdGROgfvJ+F3mf6pxjVa1V0uaiu41To6MSZTeL3X7yE09E8sx7ZIHPajYfa88mE9C8raAnCsbD9ANiyGxaE5TC67JdiRZdZ6xMib95Z9QWmlIsYjXXZ77kXzOQjyIN5S9luTcpb3jOe1N0rynbRqNytJuOuvuqBnCMcyW9ZRCV1tIg8NcNA4RvUNWLvRcnHw7ARA1Na+Wg==,iv:kMlf9irSs5eYE2yhTejIE4tu9QT0FzmdyatI6rVqYKI=,tag:3q7WBi1sjZtzirNIWzpo2Q==,type:str]
DNS_KEY_SECRET: ENC[AES256_GCM,data:og5LAa0Us+NPt0exBTIAUwUc7L/WqWhLSvncDBKluE7j27w5n6fVmuSbf+0PGM9Kgy1YJh4ZcZrEzjiMjnM1jbSH3IO1jM/hNxhrNC2GpM2vnzRP0T4oRA==,iv:IxQrKSa2gbrd3VP78f95uAbzeK23gKY5rU4tjwdjfk4=,tag:8pH/SYIDiCx0oDsQaDd5hQ==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Kzk0VjhzelRHY1hIVGlv
            cHZHaVZPcjV0K3NKZzRnK25EeUtzdjRrRmlRCkpYWk5ya2dzVzRVdWRPZzBVU2VJ
            NFRFcEljblM5clprOVpYNmxzQzlWeVUKLS0tIFMzM2NtZlVCZWZ1L1dKNHB0T2Y5
            U3pYTlJ1Uy9GdnI3UG5oUzAyQWN5eVkKz9nfrhDsIqUX1EXv4pw+tiikRj+WkaG1
            0DNdG0Wruj1VDJJQT+Tk275/kIFCGPdmq+UcRMbKY3q1pYQS1LEl+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T20:11:39Z"
    mac: ENC[AES256_GCM,data:UEG1CvBj70/5f5ebayobof+/G7bzOnOl4S+NUh0VDxqcxEOEjYc0EvVdYm6qnP6CwGeNy8kMy9fzN3v5TStxymTCkBDPI6Jx5i2NE6JPQqr/SXLhJxitjqNIDYwK540P1dN0GZDFw2Ra2IAK67w3YZLTsaohGl56O/nI85CCOvE=,iv:urqIrSmsWz3PmVTdVOMgdrJi5f2TgBTMJc3inrVEDxk=,tag:dtAxSEd/4XaehCjsznrfHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
